### ISSUE TITLE
UN65KS850 - UnhandledResponse ms.channel.timeOut

### ISSUE THREAD

**Issue by ingenium13** [Ape/samsungctl#53] opened 2017-10-05 23:24 UTC
I have a UN65KS850 (2016 curved model) that appears to use websockets. When I try to use this tool, it throws:
```
python -m samsungctl --host <IPADDRESS> --method websocket KEY_POWER
  File "samsungctl/remote.py", line 10, in __init__
    self.remote = RemoteWebsocket(config)
  File "samsungctl/remote_websocket.py", line 25, in __init__
    self._read_response()
  File "samsungctl/remote_websocket.py", line 67, in _read_response
    raise exceptions.UnhandledResponse(response)
samsungctl.exceptions.UnhandledResponse: {u'event': u'ms.channel.timeOut'}
```
I've tried specifying other flags such as ID and changing the keycode, but it makes no difference. I also don't receive a request on my TV asking about allowing access (as others have implied may happen).

Output of wireshark:
```
Not shown: 65522 closed ports
PORT      STATE SERVICE
7676/tcp  open  imqbrokerd
7678/tcp  open  unknown
8000/tcp  open  http-alt
8001/tcp  open  vcom-tunnel
8002/tcp  open  teradataordbms
8080/tcp  open  http-proxy
8187/tcp  open  unknown
9119/tcp  open  unknown
9197/tcp  open  unknown
9999/tcp  open  abyss
10443/tcp open  unknown
15500/tcp open  unknown
49326/tcp open  unknown
```

**Comment by cnf** [comment] 2017-10-23 13:47
same happens on an UE55KS7000

**Comment by Ape** [comment] 2017-11-02 06:48
Duplicate of #22

**Closed by Ape** 2017-11-02 06:48 UTC

**Comment by cnf** [comment] 2017-11-03 12:08
Edited by @Ape:
I hijacked this issue to collect all instances where some random TV model does not work, but we don't know what is the cause or how it could be fixed.

Isn't the problem that the code isn't handeling `ms.channel.timeOut`, and throwing a traceback for it?

**Comment by Ape** [comment] 2017-11-03 18:30
@cnf Well, handling this `ms.channel.timeOut` wouldn't by itself enable any functionality on this TV model.

**Comment by eclair4151** [comment] 2017-11-21 16:31
@ingenium13 
hmm the K series Tvs should be supported. If you get the app MyTifi from the iOS app store or This for android
https://play.google.com/store/apps/details?id=wifi.control.samsung&hl=en

try to use them. When you connect does it ask you to enter a PIN or is there just a button that says allow
