### ISSUE TITLE
Doesnt seem to work with the folowing TVs:

### ISSUE THREAD

**Issue by WiseSage17** [Ape/samsungctl#74] opened 2018-01-18 13:15 UTC
`{
  "id": "uuid:Something",
  "name": "[TV] UE65J6200",
  "version": "2.0.25",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "uuid:Something",
    "model": "15_HAWKM_2D",
    "modelName": "UE65J6200",
    "description": "Samsung DTV RCR",
    "networkType": "wired",
    "ssid": "",
    "ip": "192.168.***.***",
    "firmwareVersion": "Unknown",
    "name": "[TV] UE65J6200",
    "id": "uuid:SOMETHING",
    "udn": "uuid:SOMETHING",
    "resolution": "1920x1080",
    "countryCode": "GB",
    "msfVersion": "2.0.25",
    "smartHubAgreement": "true",
    "wifiMac": "**:7d:**:c4:**:2d",
    "developerMode": "0",
    "developerIP": "192.168.*.*"
  },
  "type": "Samsung SmartTV",
  "uri": "http://192.168.*.*:8001/api/v2/"
}`

`{
  "id": "Something",
  "name": "[TV] UE48JU6500",
  "version": "2.0.25",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "uuid:Something",
    "model": "15_HAWKM_UHD_2D_SC",
    "modelName": "UE48JU6500",
    "description": "Samsung DTV RCR",
    "networkType": "wired",
    "ssid": "",
    "ip": "192.168.**.**",
    "firmwareVersion": "Unknown",
    "name": "[TV] UE48JU6500",
    "id": "uuid:Something",
    "udn": "Something",
    "resolution": "1920x1080",
    "countryCode": "GB",
    "msfVersion": "2.0.25",
    "smartHubAgreement": "true",
    "wifiMac": "**:f1:**:fb:**:8d",
    "developerMode": "0",
    "developerIP": "192.168.**.**"
  },
  "type": "Samsung SmartTV",
  "uri": "http://192.168.**.**:8001/api/v2/"
}`

`{
  "id": "SOMETHING",
  "name": "[TV]Samsung LED40",
  "version": "2.0.24",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "SOMETHING",
    "model": "14_NT14U_2D_BT",
    "modelName": "UE40HU7000",
    "description": "Samsung TV RCR",
    "networkType": "wired",
    "ssid": "",
    "ip": "192.168.1**.**",
    "firmwareVersion": "Unknown",
    "name": "[TV]Samsung LED40",
    "id": "SOMETHING",
    "udn": "SOMETHING",
    "resolution": "1920x1080",
    "countryCode": "GB",
    "msfVersion": "2.0.24",
    "smartHubAgreement": "true",
    "developerMode": "0",
    "developerIP": "0.0.0.0"
  },
  "type": "Samsung SmartTV",
  "uri": "http://192.168.**.**:8001/api/v2/"
}`

Using the following commands:

PERCYS-MacBook-Pro:Desktop PERCY$ samsungctl --host 192.168.**.** --port 8001 KEY_MENU
Error: Connection closed!

**Comment by Ape** [comment] 2018-01-19 19:11
J or H series models are not currently working.

This is duplicate of #22.

**Closed** 2018-01-19 19:12 UTC
