### ISSUE TITLE
Authentication on TV each time i user samsumgctl

### ISSUE THREAD

**Issue by zechasso** [Ape/samsungctl#48] opened 2017-08-13 08:08 UTC
Hi there,
I get the authentication message on TV each time I use samsungctl.
I have to agree it, afterwards the sent key-command is executed.
Can you tell how to solve this problem please?

**Comment by Ape** [comment] 2017-08-14 06:56
#16 might be related.

**Comment by YuriGuzun** [comment] 2017-09-09 20:10
Try to pass same --id value

**Comment by peterberbec** [comment] 2017-09-16 22:13
@zechasso - I had the same problem. YuriGuzun's solution worked perfectly for me. I just picked a number and stuck to it, works great now.

**Comment by Ape** [comment] 2017-11-02 06:43
Duplicate of #16.

**Closed by Ape** 2017-11-02 06:43 UTC
